- lib/header.js
- lib/render.js
- package.json
As per an earlier discussion with @juliangruber:
I suggest to revert this (at least for now). Sharing a header module between dat-desktop and dat.land seems to complicate things, as the headers will most likely have a different layout and maybe even consist of different components.
As currently things are still moving a lot and we are in exploration mode, I suggest to stick to this workflow for styles, which makes it much easier for me to iterate quickly:
- Keep all styles that are reusable in dat-design. Use classes, keeping in mind that they should be reusable and component-oriented (I follow this flavor of the [BEM naming convention](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/), which is not pretty but helps to keep our CSS more robust and readable as …
> Revert "refactor out header.js into dat-header"

- index.js
- lib/delegate-electron-events.js
- package.json
Lil maintenance patch to clean up `index.js` - gives us some room to add more features. Think this is cool because it turns the entry file for electron into something that weighs 30 lines of code that's easy to follow :sparkles:
- use `envobj` to validate environment variables
- create `lib/delegate-electron-events` to wrap boilerplate in `index.js`, needed to safely delegate file and link events sent to electron while booting (should turn into a package at some point probably)
- use `electron-window` to remove some of the browser boot boilerplate
> feat(index): use electron-window

- app.js
- elements/table.js
- models/main-view.js
- models/repos.js
- package.json
- pages/main.js
- renamed `models/app` to `models/repos`
- created a `main-view` model used to handle the state from `views/main`
- added `choo-persist` v2 that auto-persists all state except `models/repos` to `IndexedDB`. `models/repos` cannot be persisted because the values inside it cannot be serialized
- created a welcome screen that's shown the first time you boot up the application - didn't do any styling so @Kriesse can do her thing
---
- https://github.com/datproject/dat-desktop/issues/68
---
> add unstyled welcome screen

- models/repos.js
- package.json
Uses `opener` for cross-platform file opening compat. Had to fork it because of an issue with the Acorn parser, which is solved by https://github.com/domenic/opener/pull/22 - I've pointed it to our fork in the mean time. Thanks! :sparkles:
> use open to open files

- package.json
Prior to this the browserify bundles would contain paths like `/Users/julian/...` which wouldn't work on other machines, as @Kriesse noticed.
To fix this, I had to remove the `--no-commondir` option (by removing `--node` which required it and adding back the remaining options of `--node`). This would end us up with paths like `/node_modules/leveldown/...` though, which also wouldn't work. Paths need to be `./node_modules/leveldown/...` etc.
To fix this, I first forked the bindings module to https://github.com/juliangruber/bindings-browserify, which makes paths relative here: https://github.com/juliangruber/bindings-browserify/blob/master/index.js#L71. We're using the aliasify module (https://github.com/benbria/aliasify) to make every module require that instead of the regular bindings …
> fix bundle not to contain absolute paths

- package.json
- scripts/browserify.js
`__dirname` is now being resolved correctly, so it will work on any machine and in the packaged app as well. Also as a benefit not the `"bundle"` and the `"watch"` scripts always use the same browserify arguments.
> Fix browserify bundling

- package.json
- scripts/build
Adding the `--build-from-source` flag fixed issues for @karissa installing the deps. While this bypasses prebuild logic and we should investigate why that fixes it, it seems to work for now.
This PR moves the build logic back to our build script.
> move back to rebuild script

- app.js
- package.json
- scripts/browserify.js
Should help boost performance a lil; ref https://github.com/datproject/dat-desktop/issues/152
- start using `envify` to hardcode strings for production
- only run `choo-log` if `NODE_ENV` is development
> only run choo-log in development

- index.js
Only allow single instance of app to be open at any given time. This doesn't guard against trying to open leveldb /indexeddb multiple times though. Closes #150
> allow only single app instance

- package.json
- scripts/browserify.js
@Kriesse can you give this a try? This should fix the sodium errors without special casing any dependency.
> fix sodium-prebuilt using updated bindingify

- scripts/build
Originally introduced to fix native dependency issues, we found
out that browserify configuration was to blame instead. So this
enables prebuild installs again!
> scripts/build: remove --build-from-source

- models/error.js
this way we get the clickable code locations in the dev tools
> models/error: properly rethrow error, preserving stack

- scripts/browserify.js
My bundle was not working because the path of the repo included `node_modules`. Make sure we only ignore node_module files relative to the repo directory.
> fix bundle if dat-desktop parent is node_modules folder

- package.json
- scripts/build
so CI builds contain the bundle, which is currently missing
> add bundle to postinstall, for CI

- elements/table.js
Doing text transform capitalize can lead to weird author things like: 
Also some people like their name lower case. We should use whatever the author specified.
> Do not capitalize author

- models/main-view.js
- models/repos.js
- pages/main.js
> welcome screen should show every time you open the app as long as you have no dats
Show welcome screen when no dats are available as per https://github.com/datproject/dat-desktop/issues/138
> reset welcome screen

- elements/crash-modal.js
- models/repos.js
In light of #223 it might make more sense to have a directory to store our config in; when moving our config from `indexedDB` into `toiletdb` this could serve to hold our config files. I suspect it might also help make migrations between versions easier. Thanks!
> update db location

- elements/status.js
- elements/table.js
- models/repos.js
This PR makes sure we are properly importing files into the dat and rendering the status. 
- We weren't calling it at all. Now it'll import the files and update the table on every file import event.
- Modularizes out the progress bar rendering code. 
- Removes the progress bar for local dats that the user owns (shared dats). This is consistent with the CLI. The reason we made this decision in the CLI is that it is very difficult to tell what the progress is for a dat now. So instead, it will say 'Watching for updates' where the progress bar used to be. 
- Because the dats could be downloaded remotely or created locally, the header says 'Status' instead of 'Downloaded'
> make sure that create new dat works as intended with stats

- elements/confirm-modal.js
- elements/table.js
- models/repos.js
- pages/main-delete.js
This fixes the issue where multiple deletions in a row caused the wrong `dat` to be referenced and crashed the app. The core issue at hand is most likely events not being copied over correctly and referencing old state. Thing seem to point to a `morphdom` issue. Made a note to test this in https://github.com/datproject/dat-desktop/issues/223#issuecomment-279685613.
In the meantime I've solved the issue by creating a temporary variable to store the pending key for deletion.
Had to move a lot of code around to pinpoint the issue; apologies for the rather large diff here.
> fix multiple deletions in a row

- app.js
The barracks API isn't great - my bad; this should hopefully fix the issue @Kriesse encountered.
> fix createSend syntax

- index.js
Greetings Dat team :wave: 
This pr addresses #252 (no min-height, allowing the window to become very short)
I thought that 395px was a nice min-height.
Screenshots of dat-desktop at the minimum height below:
> sets electron window minHeight to 395px

- pages/main.js
This pr addresses #206 (Welcome screen should be dismissible with the keyboard)
With these changes the user can press Space or Enter to dismiss the welcome screen.
At first I tried to add a keypress eventListener to the `<main>` element.  However, I learned that electron [requires a bit of machinery to listen to key events in the DOM](http://stackoverflow.com/questions/40763427/electron-does-not-listen-keydown-event).  I figured that it would be less code across the project if I added a keydown eventListener to the window, and then promptly removed it if the Enter or Space keys were pressed (also on the `onexit` method), and then send an action to the `toggleWelcomeScreen` reducer.
I hope these changes work well for you, and congratulations on the launch!
> Makes welcome screen dismissible with Enter or Space

- models/repos.js
https://github.com/datproject/dat-desktop/pull/274 introduced a regression that opened dirs on MacOS in the background - this fixes the regression. Thanks!
- Reference Electron issue: https://github.com/electron/electron/issues/4951
> open macos dirs in foreground

- elements/status.js
- package.json
should afterwards be cherry-picked into v1.1.0 as well.
Needed a bug fix in dat-worker and forgot to convert to kilobytes
> fix network speeds. closes #287

- models/repos.js
`multidat.close()` also removes the dat from the db, however we only want to "close".
> models/repos: fix accidental removal of all dats on quit. closes #298

- .travis.yml
the fix was to make sure the DISPLAY variable was set globally. Yay for automatic Linux builds again!
> fix linux builds on travis

- elements/status.js
- elements/table.js
- index.js
- models/repos.js
This gives us global cross platform process indicators, a la
In order to enable this, I moved calculation of a dat's progress value from the views to `models/repos`.
The total progress value is calculated by averaging the individual progress values of all dats who haven't completed yet.
> add global progress indicator. closes #296

- index.js
- lib/browserify.js
In dev we would start the app once the bundle was generated, but didn't wait until it was actually written to disk. Sometimes though, you wouldn't see the current version of it.
> fix app starting before the bundle has been written

- package.json
Adds support for choo's timing API added in `v5.1.0` - helps us keep track if our UI is slow (e.g. `<60fps`), which it kinda appears to be 🙁
> bump choo deps

- elements/modal.js
@yoshuawuyts do you maybe see a cleaner solution? Maybe something like
```js
button.green('Yes, Remove Dat', {
class: 'fr ml3 confirm-button',
onclick: ondelete,
focus: true
})
```
> elements/modal: fix missing button focus. closes #309

- elements/dat-import.js
- elements/empty.js
- elements/header.js
New copy should improve conversion rate of users that go from downloading the binary to sharing data!
CLI uses 'clone' for a Dat -- open to replacing 'download' with that, except right now there is no multi-writer so 'download' is more accurate to what is actually happening here.
Please discuss, thanks! 🎉
> Change copy to be consistent with CLI

- lib/dat-manager.js
- package.json
The speed display was updating so fast that it was hard to use, this limits it to one update per second.
In another iteration we can make sure that all the rows update at the same time, in synchronicity.
This also reduces CPU load :)
> throttle stats updates to once per second. closes #357

- lib/dat-manager.js
we were only reading the metadata from disk, which wouldn't work in the case where you want to know the meta of a dat that you just began downloading. this patch changes it to _always_ read metadata from the feed, and only write to disk.
> dat-manager: fix metadata handling by reading dat.json from stream, not disk. closes #378

- models/dats.js
- package.json
in previous versions of toiletdb, the initial state wouldn't be
read properly, thus causing weird issues like deleting all dats
by accident.
> fix accidental deletion of all dats

- .travis.yml
npm bundles with node 8 aborts installation if the browserify step fails, see https://github.com/datproject/dat-desktop/issues/436
> travis: test on node 8

- lib/dat-manager.js
- models/dats.js
- models/intro.js
This PR fixes two things that I found out by trying to change the tests from tape to tap in #453 .
1. On instantiation using `createManager` the `onupdate` call is called **before** the return. Which is a bad case of zalgo that happens to interact with `models/dats` and `models/intro`
2. Timing issues may occur if a dat that is supposed to be deleted or disconnected and then triggers an unexpected event the network connection is established and possibly never stopped.
> Fix for the order dats are loaded

- lib/dat-manager.js
- package-lock.json
- package.json
- tests/dat-manager.js
The new `.disconnect` method in https://github.com/datproject/multidat/pull/12 and https://github.com/datproject/multidrive/pull/14 allows to write more stable tests and should leave less connections in limbo if used properly on app shutdown. ~~Since both references PR's are not yet merged this PR is marked `[WIP]`~~
> Using new disconnect method to stabilize tests

- package-lock.json
- package.json
- webpack.config.js
During debugging some connection issue on the react branch I found that [`utp-native`](https://github.com/mafintosh/discovery-swarm/blob/101bbc733ae696e9f7fc8aa8fe450c98b552e0a3/index.js#L16) couldn't be loaded and as a result `utp` wasn't available.
`utp` is loaded through [`node-gyp-build`](https://github.com/mafintosh/utp-native/blob/9639b375d98686c46c9f173b69da138c112454f9/index.js#L5) whichs `load`-method has a [wildcard-require](https://github.com/mafintosh/node-gyp-build/blob/8d69247eca6f6c00a1437e5093c8d281d3a4ed36/index.js#L13), resulting in following warning:
```
WARNING in ./node_modules/node-gyp-build/index.js
13:9-32 Critical dependency: the request of a dependency is an expression
at CommonJsRequireContextDependency.getWarnings …
```
> Prevent "webpacking" of native dependencies

- app/components/dat-import.js
In the react branch we have a temporary link on the Import-Dat UI element, this PR removes it in preparation for the react release.
> Removed temporary link in the import-dat ui element.

- app/actions/dat-middleware.js
- app/actions/index.js
- app/components/button.js
- app/components/dat-import.js
- app/components/header.js
- app/components/status-bar.js
- app/components/status.js
- app/containers/header.js
- app/index.js
- app/reducers/index.js
- package-lock.json
- package.json
In a future PR I need to specify the home director for DAT operations. This PR also moves globals of actions (`dats`) from [a global variable](https://github.com/dat-land/dat-desktop/blob/af328a1d5ca2a3dcfcfc3959d3bc42832accf2b0/app/actions/index.js#L12) into a [class/instance system](https://github.com/dat-land/dat-desktop/blob/a5e2aa180e689a34789bbce91ae94af7afa915f9/app/actions/dat-middleware.js#L19). This also turns the [`LOAD_ACTION`](https://github.com/dat-land/dat-desktop) - (_which wasn't a real action_) in [`./app/index.js`](https://github.com/dat-land/dat-desktop/blob/af328a1d5ca2a3dcfcfc3959d3bc42832accf2b0/app/index.js#L26) into an [`regular operation`](https://github.com/dat-land/dat-desktop/blob/a5e2aa180e689a34789bbce91ae94af7afa915f9/app/index.js#L31).
It also …
> Extracted actions into middleware

- app/components/viewer/index.js
- app/components/viewer/preload.js
- app/viewers/text/index.js
Looking over #515 I wondered how a different API could look like that more future proof to our case. I came up with the API in this PR. Essentially it adds following things:
1. It adds a very simple streaming implementation - in case one just wants to stream the whole file
2. It adds a `initViewer` command to init one viewer; subsequently `viewer:open` events are called which each should be triggered when someone opens the webview - this way the viewer can theoretically be reused in future iterations instead of respawned for each file
3. It uses dat links with versions as file reference which should make sure that the preview always loads the correct data from the correct dat archive. Aside from this helping debugging, it should help to figure out timing problems in the user interface …
> React Viewer: Streaming API (and other tweaks)

- app/index.js
- package-lock.json
- package.json
When developer-tools are active in electron, drag&drop stops working (See: https://github.com/electron/electron/issues/3647) This PR uses an [improved version](https://github.com/martinheidegger/electron-drag) of [`electron-drag`](https://github.com/kapetan/electron-drag) to enable drag & drop.
> Fixed header drag & drop

- index.js
- package.json
Backstory: Just tried (for far too long) to find out why osx-mouse isn't running at my colleagues computer. It turns out that the node/npm version that built the module was a different one than what was bundled with Electron.
This PR adds a warning when you start electron that the version used in the command line is different from the version bundled with electron. This way any team member that might run into the same issue will be warned as well.
> Warning about different Node Version

- .gitignore
- package-lock.json
There is almost every day an update in an installed dependency, which causes every time a change in `package-lock.json`. 
This PR will untrack `package-lock.json` from the Git repository. If specific versions are required for certain dependencies, then the settings should be made accordingly in `package.json`.
> Removes package-lock.json from the repository

- app/components/status-bar.js
- static/base.css
Before this PR the window couldn't be used properly with the developer tools open. This means that styling test were hard to do.
After this pull request, scrolling should be possible even if the window
is less than the minimum width.
> Fix: dev tools at minimum window width

- app/consts/screen.js
- app/containers/download.js
- app/containers/intro.js
- app/containers/status-bar.js
- app/containers/table.js
- app/reducers/index.js
The screen-identifiers are strings. By extracting all existing identifiers into a constant-module we can now have code-suggestions in an IDE (ms vscode for example)
> Extracted screens into constants

- app/consts/screen.js
- app/containers/download.js
- app/containers/inspect.js
- app/containers/intro.js
- app/containers/status-bar.js
- app/containers/table.js
- app/reducers/index.js
I noticed that an error with the Inspection screen.
It tried to update the inspected DAT even when navigating to other screens.
https://github.com/dat-land/dat-desktop/pull/562/files#diff-bf58091931fe43a77612c0916614753dL8
This PR now updates the dat only when the inspect screen is selected.
This PR is based on #561
> Fix: Update inspection data only in "inspect" screen

- app/components/button.js
The master branch was giving off a warning about the "extend" API. This replaces it with the new "styled" API.
For reference here is the original error:
```
ThemeProvider.js:28 Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546
(anonymous) @ ThemeProvider.js:28
```
> Fixed deprecated syntax in StyledComponent.

- README.md
The travis badge was still pointing towards datproject.
> Corrected travis-badge location

- app/actions/dat-middleware.js
The Fileview list didn't update (or show `N/A`) in a many cases, such as:
- When a new DAT was created.
- When looking at a DAT after the preview was shown.
This PR should fix both cases.
> [WIP] FileList View

- app/actions/dat-middleware.js
- app/components/table-row.js
Even if you cancel the download of a DAT, the DAT is continuously downloaded by DAT-desktop.
The reason for this is that in the middleware on the `CANCEL_DAT` action it receives an object with the `key` property:
https://github.com/dat-land/dat-desktop/blob/e458a4a59a2a44a33c588deb8d23b6a8a5bd0708/app/actions/index.js#L38-L39
https://github.com/dat-land/dat-desktop/blob/e458a4a59a2a44a33c588deb8d23b6a8a5bd0708/app/actions/dat-middleware.js#L29
... but it is treated as string when canceling the DAT ...
https://github.com/dat-land/dat-desktop/blob/e458a4a59a2a44a33c588deb8d23b6a8a5bd0708/app/actions/dat-middleware.js#L293-L294
This PR fixes this by assuming the `{key}` property for every command.
> Fix: Press "cancel" on download-preview-screen continues to walk dat.

- README.md
I cleaned up the Readme file and removed outdated (and wrong) content. 
The first paragraphs had been aligned, which requires to use HTML content in Markdown, which I would like to avoid, if possible. I prefer to use default styling.
> Simplified Readme and Markdown syntax check

- app/index.js
- package.json
Node 10.2 has a gyp problem which lead to `osx-mouse` not compiling properly: Effectively `electron-drag` has become not-supported. But it seems like dragging the header does work without it as well?!
> Removing drag-and-drop as it is incompatible with electron 3

- app/components/title-field.js
- app/containers/drag-drop.js
Title that were editable need to be clicked before the user can edit text.
This problem seems to have been caused by the update to styled-components v4
But even after a save: the title isn't stored because of https://github.com/dat-land/dat-desktop/pull/602/files#diff-84f92d50bee815f7173b3515a7313e7fL63
This PR fixes the behavior: Now the users can immediately change the title:
> fixed: focussing on title-edit

- app/actions/dat-middleware.js
If the settings aren't stored properly (either empty string or malformatted json) the application doesn't start (white screen).
This PR changes the startup behavior to ignor existing errors.
> fix: broken dat settings break app start.

- app/components/button.js
styled-components deprecated the `.attr({})` syntax [in version 4.1.0](https://github.com/styled-components/styled-components/releases/tag/v4.1.0).
The recommended syntax is `.attr(props => ({}) )`.
PR is fixes the deprecation.
> fix: deprecated syntax by current styled-components.

- app/consts/state.js
- app/reducers/index.js
As part of a refactoring process where I would like to clean up the react state _(it is currently polluted with problematic data)_. I extracted the `defaultState` into its own file. As part of the process I also moved it into a function to prevent changing of the data by accident.
> refactoring: moving "defaultState" moved to consts.

- app/components/file-list.js
- app/components/inspect.js
This PR cleans a few style issues in the file list:
1. It puts the size at the right sight of the line.
Before: ![line-right-before](https://user-images.githubusercontent.com/914122/49348823-141d1d80-f6eb-11e8-816e-371ffd15c88a.png)
After: ![line-right-after](https://user-images.githubusercontent.com/914122/49348827-17b0a480-f6eb-11e8-920f-14b647e569e7.png)
2. It fixes the `odd` line style to actually work ;). It also changes the contrast from `--color-neutral-04` to `--color-neutral-10` in order to for the lines to be better distinguishable from the background.
| Before | Before - fixed | After |
|---|---|---|
| ![lines-before](https://user-images.githubusercontent.com/914122/49348932-8aba1b00-f6eb-11e8-80d0-a054a6ead44a.png) | <img alt="screen shot 2018-12-03 at 11 13 48" …
> Style improvements: file list

- index.js
- package.json
There may still be a bug I am not able to identify. Clicking "Get Started" has no effect.
> fix: update Electron, comment deprecated makeSingleInstance call

- README.md
/releases leads to https://github.com/datproject/dat-desktop/blob/master/releases which is a 404 I suggest reverting to the absolute url. 
Thanks for what you people do, long life to the dat protocol :D.
> Revert to absolute url for releases
