datproject/dat-desktop

app.js
package.json

store files of disk instead of leveldb

---

app.js
lib/render.js
package.json

add title display from dat.json

---

pages/main.js

improve progress bar and hexagon

---

lib/create-archive.js
package.json

Use dat-node 0.1 instead of dat-js!

use dat-node

---

.gitignore
app.js
index.html
lib/transform.js
package.json

Add browserify

---

README.md
app.js

But also like fix a missing link and remove some unused deps, hah :sparkles: - well-scoped PRs! :tada:

fix(docs): update for new build commands

---

package.json

Use https://github.com/yoshuawuyts/bindingify rather than something inline :tada:

feat(deps): use bindingify

---

elements/modal.js
lib/modal-element.js
models/app.js
package.json
pages/main.js

Phoo, this required a good amount of fixes to fringe libraries but think it should be all good now; replaces the modal element we were using with a new one. Would be neat if someone could try and run it to see if it works for them. Didn't really invest much into styling stuff but I figured @Kriesse would be happy to polish it to a better state haha :sparkles:
All the stuff in `lib/` should be moved into a separate package (base-elements ?), but gonna reserve that for another PR hah. Thanks!
--- 
Todo: add screenshot

feat(modal): split off

---

lib/dat-manager.js

Closes https://github.com/datproject/dat-desktop/issues/104 - thanks!

fix(dat-manager): fix removing a dat

---

elements/table.js
package.json
pages/main.js

- moved the table element from the main view to `elements/table.js`
- created an empty state for the main view that's shown if there are no elements in the thing - meant to be styled by @kriesse as per #68 
- use the `prettier-bytes` package to make our byte display a bit less noisy
- "delete a dat" is broken as per https://github.com/datproject/dat-desktop/pull/91 - fixed some of the symptoms but it's still not working - opened an issue for it here https://github.com/datproject/dat-desktop/issues/104
Thanks!

Vanilla empty state

---

elements/modal.js
lib/modal-element.js
models/app.js
pages/main.js

Implements the final modal features. Ref #103

feat(modal): show dialog text

---

elements/modal.js

- resolve regressions introduced in the styles patch
- split off some long lines into multiline statements

fix(modal): resolve merge errors

---

elements/dat-import.js
elements/modal.js
elements/table.js
pages/main.js
public/css/base.css
public/css/colors.css

Style modal true to mockup

---

elements/dat-import.js
elements/header.js
elements/modal.js
elements/table.js
package.json
pages/main.js

use sheetify nested syntax

---

app.js
models/repos.js
models/window.js
package.json

@yoshuawuyts can you take over hooking this into the model code?
fixes #85

Add drag and drop code

---

models/error.js
package.json

Reports to our endpoint whenever the application crashes. Closes #21

add crash reporting

---

elements/table.js

Closes https://github.com/datproject/dat-desktop/issues/136

add default author to ui

---

models/main-view.js
models/repos.js
package.json

realized `choo-model` is not ideal hah; just moving some code around (:

remove choo-model

---

models/main-view.js

Oops - spotted this while writing tests to make sure this worked haha 😅

fix main-view reducer

---

pages/main.js

fix misalignment of empty state svgs

---

models/repos.js

Turns out events have changed and we were making mistakes soooo, here goes

fix dat events

---

index.html
models/main-view.js
models/repos.js

Makes it so the welcome screen is only shown when theres no dats, and stays dismissed after.

fix dat boot screen

---

models/repos.js

types were mismatched, this fixes it :sparkles:

fix creating a dat

---

elements/table.js

Related issues
==============
- https://github.com/datproject/dat-desktop/issues/182

fix progress bars

---

elements/table.js

fix stats when creating a dat and viewing peers

---

elements/dat-import.js
elements/header.js
pages/main-delete.js
pages/main-error.js
pages/main-share.js
pages/main.js

Wait to render header until the database is ready. Fixes https://github.com/datproject/dat-desktop/issues/215

render header when ready

---

elements/table.js

Fixes this error i was seeing:

fix bytes output error

---

elements/button.js
elements/confirm-modal.js
elements/link-modal.js
elements/table.js

…by adding title and aria-label attribute properties. 
Later: refactor as as described in #219.
Related: #183 (let's build prettier tooltips on top of this)

make button element more accessible 

---

app.js
elements/dat-import.js
elements/error-modal.js
elements/header.js
models/error.js
models/repos.js
pages/main-crash.js
pages/main-delete.js
pages/main-error.js
pages/main-share.js
pages/main.js

Allows us to gracefully handle errors instead of crashing the app. Addresses #209

Catch errors

---

lib/browserify.js

Fixes a bug where envify would accidentally hard code the wrong
variables

fix envify

---

models/error.js

Had a lil regression with the error messages; this restores it (:

fix error messages

---

elements/table.js

Fixes https://github.com/datproject/dat-desktop/issues/254

fix table-element title

---

README.md

Fix for https://twitter.com/jensnikolaus/status/834064238490615808. cc/
@juliangruber

add clearer install instructions

---

README.md

- Includes `brew cask install` (closes https://github.com/datproject/dat-desktop/issues/218)
- Created table of content
- Rewrote install section
- Changed the tagline to what we've been using on social media
Thanks!
__edit:__ [preview](https://github.com/datproject/dat-desktop/blob/c5c64b8919f540a88533dced5342eeb0c2287ebf/README.md)

rework readme

---

elements/status.js
elements/table.js
lib/auto-updater.js
lib/browserify.js
package.json

needs to be tested thoroughly, but this should let @Kriesse get started with the design

add WIP progress text

---

elements/table.js
package.json

This affects icons only and can be merged already.
The new icons are not yet added to the UI, but are needed for further styling work on #266.
Also contains a little improvement of the network status icon.

add new status icons. improve styling of network icon.

---

.travis.yml

until travis linux builds are fixed, so I can focus on higher priority issues

travis: remove linux for now

---

models/repos.js

We were getting one listener on this event per archive and app instance

fix listener warning on app.on("before-quit") event. closes #270

---

elements/button.js
elements/status.js
elements/table.js
models/repos.js
package.json

@Kriesse can you take over with some styling? I needed to turn the status hex icons into buttons, but this is how it looks with my changes:

Add pause/resume. Closes #266.

---

elements/status.js

moved keyframes out of :host css and IT WORKS

make loading animation of progress bar work

---

elements/modal.js

Set a max-width on error modal and fix misaligned checkmark icon.
As mentioned in https://github.com/datproject/dat-desktop/issues/311

Fix modal style

---

elements/modal.js

Modal text cannot overflow anymore

---

elements/table.js
models/drag-drop.js
models/repos.js
models/welcome.js
pages/main.js

Implements namespaces & dashes for event names. Ref #318. Thanks!

implement namespaces

---

package.json
tests/welcome.js

Adds some basic unit tests. Not everything is testable yet, but feel we can solve that in due time.

add unit tests

---

elements/table-row.js
lib/dat-manager.js
models/error.js
package.json

Closes #284
This needs UI still, it currently looks like this:

Add individual dat init error states. Closes #284

---

elements/header.js
models/dats.js

Closes GH-335 - should at least allow people to save to external storage (:

let users select download location

---

app.js

We removed this in #280 but oops, forgot to also remove it here.

fix extra css call

---

elements/table-title-field.js

Only owner should be able to show the inline file editing interface. fixes #347

BUG: Only owner should be able to inline edit the title.

---

assets/base.css
elements/table-row.js
elements/table.js
package.json

This is a WIP pull request for https://github.com/datproject/dat-desktop/issues/180, needs styling still.

add fade-highlight to new dats. closes #180

---

elements/dat-import.js
elements/header.js
elements/table-row.js
elements/table-title-field.js
lib/dat-manager.js
package.json

this hopefully fixes some of the rendering issues

upgrade microcomponent to v3

---

elements/table-row.js

the `N/A` default value wasn't used here properly

fix network icon in case of no network. closes #365

---

elements/table.js
package.json

for https://github.com/datproject/dat-desktop/issues/359#issuecomment-302096833

remove cache-element in favor of new microcomponent

---

elements/dat-import.js
elements/header.js
elements/sprite.js
elements/table-row.js
elements/table-title-field.js

fix component names

---

elements/button.js
elements/header.js

Also simplify CSS and add new style to button component. Closes #354

Clean up button alignment in header

---

elements/table-row.js

add hover state to hex icon. closes #326

---

elements/table-row.js

mouseleave isn't reliable enough for this

fix hex hover effect through mousemove event. closes #394

---

elements/header.js

explicitely set font-size on share button. closes #392

Fix font-size on share button

---

elements/table-row.js

This should align the error style. I had trouble reproducing the error, so still needs to be verified visually. Closes #399

Align error style

---

elements/download.js
elements/file-list.js

later to be used by the inspect screen as well

refactor file-list into element

---

elements/table-row.js

this currently looks like this so I think it needs more styling:

Fix deleting error dats. Closes #400.

---

elements/intro.js

for some reason the onload handler isn't firing. @yoshuawuyts do you have an idea?

add ESC to dismiss intro

---

elements/dat-import.js
elements/header.js
pages/main.js

for #271 
The menu is still unstyled and the button to open the menu isn't clickable yet (css issue I think).
Once we have all the links in there we need, I'll make them open the target in a browser, as expected.

add basic menu to header

---

elements/table-row.js

Some breakpoint fine-tuning to accommodate small window sizes.

Improve layout on smallest window size

---

README.md

uh-oh! 😝 
:steam_locomotive::train::train::train::train::train:

fix standard badge on README

---

app/actions/index.js
app/components/app.js
app/components/status-bar.js
app/components/status.js
app/containers/status-bar.js
app/reducers/index.js

Closes #483
Looking real good now :)

Add status bar

---

app/actions/index.js
app/components/app.js
app/containers/dat-import.js
app/containers/drag-drop.js
package-lock.json
package.json

This lets you share a folder by dropping it on the window

add dat drag/drop. #472

---

app/index.js
index.js

add protocol handler. closes #473

---

app/components/table.js

oops, my mistake, I left it in :|

remove unneeded code

---

app/actions/index.js
app/components/table-row.js
app/components/table.js
app/containers/table-row.js

tiny fixes, now it's all working for me again :)

Fix integration errors

---

app/actions/index.js
app/components/app.js
app/components/button.js
app/components/intro.js
app/components/status-bar.js
app/containers/intro.js
app/containers/status-bar.js
app/containers/table.js
app/reducers/index.js

New version of the original PR https://github.com/dat-land/dat-desktop/pull/498 by @aks-, with the branch available in this repository.

Add intro screen

---

app/index.js
index.js

add open-file handler, fix open-url

---

elements/button.js
elements/dat-import.js
elements/header.js
elements/status-bar.js
elements/status.js
elements/table-row.js

I'm working on a Dat Site Browser integration, and I've decided to fix a few layout issues. 
This PR aligns a few elements of the UI that were too tight.

Fixes spacing for interface

---

.travis.yml
CONTRIBUTING.md
README.md
app/components/button.js
app/components/dat-import.js
app/components/header.js
app/components/status-bar.js
app/components/status.js
app/components/table-row.js
appveyor.yml

There have been some changes in the master branch, this PR merges the changes back in.

Merge master changes into react.

---

app/actions/index.js
app/reducers/index.js

https://github.com/dat-land/dat-desktop/pull/458#discussion_r194382667
Not sure if we should ignore completely the title update if the `dat.json` file doesn't exist.

Graceful dat.json title update

---

package.json

upgrade version string.

---

app/components/dialog.js

Fix the warning referenced in [#555](https://github.com/dat-land/dat-desktop/issues/550)

Fix warning: Failed prop type.

---

app/components/dat-import.js
app/components/dialog.js

Fix for issue [#549](https://github.com/dat-land/dat-desktop/issues/549)

Fix warning about using for instead of htmlFor.

---

package.json
static/base.css

This PR fixes Drag and drop and also highlights the UI status.

Fix: drag and drop stopped working.

---

app/components/app.js
app/components/sprite.js
app/index.js

The DAT icons have been added through the `Sprite` component to the DOM, this way every time the App was rendered, all icons needed to be processed.
This PR adds the icons once on application start and removes them from the react rendering system.

Performance: prevent re-rendering of icons.

---

app/actions/dat-middleware.js

The JSON parsing fixes seem superficial: Node.js it is not just possible that the `.json` files are empty or that the filesystem access is broken. It is also possible that the content of the .json files are misformatted. This PR just makes sure that the data is always parsed.

Extracted common logic on fix/avoid-the-white-screen

---

app/actions/dat-middleware.js
app/components/title-field.js

The title editor shows a shadow and in some situations it doesn't cover the full screen.
This PR fixes the structure in order for the shadow to cover the full area.

fix: Shadow when editing the title to cover the full screen.

---

app/components/header.js

This PR for to-re-working the overlay on menu-open.

fix: overlay on menu open.

---

app/components/table-row.js

removed hover action from dat-list-header.

fix: removed mouse-over-state on header

---

.gitignore
package-lock.json

This will greatly improve the stability of desktop going forward.

fix: add package-lock

---

.github/workflows/nodejs.yml
tests/index.js
tests/utils/waitForMatch.js

This will auto build releases for Windows. Supercedes #626 and fixes #558

Autobuild releases

---

app/actions/dat-middleware.js
app/actions/index.js
app/components/app.js
app/components/dialog.js
app/containers/dialog.js
app/reducers/index.js

added: alert on add the existed dat.

---

README.md

- [ X] I have read the [README](https://github.com/digidem/mapeo-desktop/blob/master/README.md) 
tool](https://github.com/datproject/dat).
#641 
I don't have an idea where the 'commands' link is supposed to point to.

couple of fixed links in readme.md

---

app/components/finder-button.js
app/components/table-row.js
app/consts/env.js
app/index.js
preload.js

Each OS has a different name for "File Manager", but `Finder` is definitely an OSX term only.

Attach tooltips to the Icons
